const ruyhat = [
  {
    id: 1,
    filial: "MAX WAY BERUNIY",
    address: "улица Беруни, 47, Ташкент",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "22:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 2,
    filial: "MAX WAY ATLAS",
    address: "улица Катартал, 28, Ташкент",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "22:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 3,
    filial: "MAX WAY - DRUJBA",
    address: "микрорайон Алмазар, 8/2, Чиланзарский район, Ташкент",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "04:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 4,
    filial: "MAX WAY MEGA PLANET",
    address: "улица Ниязбек, 1",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "23:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 5,
    filial: "MAX WAY AVIASOZLAR",
    address: "улица Авиасозлар, 23",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 6,
    filial: "MAX WAY RISOVIY",
    address: "Узбекистан, Ташкент, Алтынкульская улица, 10",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 7,
    filial: "MAX WAY PARUS",
    address: "улица Катартал, 60/5",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 8,
    filial: "MAX WAY MAGIC CITY",
    address: "Узбекистан, Ташкент, улица Бабура, 174/6",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "22:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 9,
    filial: "MAX WAY SAMARQAND DARVOZA",
    address: "Узбекистан, Ташкент, улица Коратош, 5А",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "22:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",

  },
  {
    id: 10,
    filial: "MAX WAY PARKENT",
    address:
      "Узбекистан, Ташкент, Яшнободский район, массив Мавлоно Риёзи, 30В",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 11,
    filial: "MAX WAY UNIVERSAM",
    address: "Узбекистан, Ташкент, проспект Амира Темура, 41/3",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "23:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 12,
    filial: "MAX WAY ROYSON",
    address: "Узбекистан, Ташкент, улица Заркайнар, 2",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "01:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 13,
    filial: "MAX WAY NEXT",
    address: "Узбекистан, Ташкент, улица Бабура, 6",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "22:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 14,
    filial: "MAX WAY MUQUMIY",
    address: "Узбекистан, Ташкент, улица Чиланзар",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "04:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 15,
    filial: "MAX WAY GRAND MIR",
    address: "Узбекистан, Ташкент, улица Шота Руставели, 9А",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 16,
    filial: "MAX WAY SAYRAM",
    address: "Узбекистан, Ташкент, улица Юнусота",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 17,
    filial: "MAX WAY MAKSIM GORKIY",
    address: "махалля Элобод",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "01:00",
    number: "+998712005400",
    openTime:"Restoran soat 10:00 da ochiladi",
  },
  {
    id: 18,
    filial: "MAX WAY SERGELI",
    address:
      "Узбекистан, Ташкент, Сергелийский район, массив Сергели-VIIIА, 11",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 19,
    filial: "MAX WAY FONTAN",
    address: "проспект Амира Темура",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
  {
    id: 20,
    filial: "MAX WAY MINOR",
    address: "MaxWay",
    WeekStart: "Monday",
    WeekEnd: "Sunday",
    amOclock: "10:00",
    pmOclock: "03:00",
    number: "+998712005400",
    openTime:"open_until"
  },
];

export default ruyhat;
